import Head from 'next/head';
import DashBoardLayout from '@/layouts/DashBoardLayout';
import { Row, Col } from 'antd';
import MonthCostChart from '@/components/dashboard/MonthCostChart';
import SpendCost from '@/components/dashboard/SpendCost';
import TypeCostChart from '@/components/dashboard/TypeCostChart';

export default function Home() {
  return (
    <DashBoardLayout title="儀表板">
      <Head>
        <title>記帳小幫手</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Row gutter={[16, 16]}>
          <Col span={24} md={16}>
            <MonthCostChart />
          </Col>
          <Col span={24} md={8}>
            <SpendCost />
          </Col>
          <Col span={24}>
            <TypeCostChart />
          </Col>
        </Row>
      </main>
    </DashBoardLayout>
  );
}
