import { Col, Row, Space } from 'antd';
import Head from 'next/head';

import Filter from '@/components/dashboard/Filter';
import MonthCostChart from '@/components/dashboard/MonthCostChart';
import SpendCost from '@/components/dashboard/SpendCost';
import Target from '@/components/dashboard/Target';
import TypeCostChart from '@/components/dashboard/TypeCostChart';
import DashBoardLayout from '@/layouts/DashBoardLayout';

export default function Home() {
  return (
    <DashBoardLayout title="儀表板">
      <Head>
        <title>記帳小幫手</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Row gutter={[16, 16]}>
          <Col span={24} md={16} style={{ height: 'inherit' }}>
            <MonthCostChart />
          </Col>
          <Col span={24} md={8} style={{ height: 'inherit ' }}>
            <Space direction="vertical" size="middle" style={{ width: '100%' }}>
              <Filter />
              <SpendCost />
              <Target />
            </Space>
          </Col>
          <Col span={24} style={{ height: 'inherit ' }}>
            <TypeCostChart />
          </Col>
        </Row>
      </main>
    </DashBoardLayout>
  );
}
